export const topicsActionTypes = {
   // GET TOPICS TYPES
   GET_TOPICS_START: "GET_TOPICS_START",
   GET_TOPICS_SUCCESS: "GET_TOPICS_SUCCESS",
   GET_TOPICS_FAILURE: "GET_TOPICS_FAILURE",

   // CREATE A TOPIC TYPES
   CREATE_TOPIC_START: "CREATE_TOPIC_START",
   CREATE_TOPIC_SUCCESS: "CREATE_TOPIC_SUCCESS",
   CREATE_TOPIC_FAILURE: "CREATE_TOPIC_FAILURE",

   // DELETE A TOPIC TYPES
   DELETE_TOPIC_START: "DELETE_TOPIC_START",
   DELETE_TOPIC_SUCCESS: "DELETE_TOPIC_SUCCESS",
   DELETE_TOPIC_FAILURE: "DELETE_TOPIC_FAILURE",

   // SELECTED TOPIC TYPE
   SET_SELECTED_TOPIC: "SET_SELECTED_TOPIC",

   // GET SINGLE TOPIC TYPES
   GET_SINGLE_TOPIC_START: "GET_SINGLE_TOPIC_START",
   GET_SINGLE_TOPIC_SUCCESS: "GET_SINGLE_TOPIC_SUCCESS",
   GET_SINGLE_TOPIC_FAILURE: "GET_SINGLE_TOPIC_FAILURE",

   // EDIT TOPIC TYPES
   EDIT_TOPIC_START: "EDIT_TOPIC_START",
   EDIT_TOPIC_SUCCESS: "EDIT_TOPIC_SUCCESS",
   EDIT_TOPIC_FAILURE: "EDIT_TOPIC_FAILURE",

   // PUBLISH TOPIC TYPES
   PUBLISH_TOPIC_START: "PUBLISH_TOPIC_START",
   PUBLISH_TOPIC_SUCCESS: "PUBLISH_TOPIC_SUCCESS",
   PUBLISH_TOPIC_FAILURE: "PUBLISH_TOPIC_FAILURE",
};
