export const coursesActionTypes = {
    // GET COURSES TYPES
    GET_COURSES_START: "GET_COURSES_START",
    GET_COURSES_SUCCESS: "GET_COURSES_SUCCESS",
    GET_COURSES_FAILURE: "GET_COURSES_FAILURE",

    // CREATE A COURSE TYPES
    CREATE_COURSE_START: "CREATE_COURSE_START",
    CREATE_COURSE_SUCCESS: "CREATE_COURSE_SUCCESS",
    CREATE_COURSE_FAILURE: "CREATE_COURSE_FAILURE",
}