export const coursesActionTypes = {
   // GET COURSES TYPES
   GET_COURSES_START: "GET_COURSES_START",
   GET_COURSES_SUCCESS: "GET_COURSES_SUCCESS",
   GET_COURSES_FAILURE: "GET_COURSES_FAILURE",

   // CREATE A COURSE TYPES
   CREATE_COURSE_START: "CREATE_COURSE_START",
   CREATE_COURSE_SUCCESS: "CREATE_COURSE_SUCCESS",
   CREATE_COURSE_FAILURE: "CREATE_COURSE_FAILURE",

   // GET A COURSE TYPES
   GET_COURSE_START: "GET_COURSE_START",
   GET_COURSE_SUCCESS: "GET_COURSE_SUCCESS",
   GET_COURSE_FAILURE: "GET_COURSE_FAILURE",

   // UPDATE A COURSE TYPES
   EDIT_COURSE_START: "EDIT_COURSE_START",
   EDIT_COURSE_SUCCESS: "EDIT_COURSE_SUCCESS",
   EDIT_COURSE_FAILURE: "EDIT_COURSE_FAILURE",

   // UPDATE A COURSE POSTS
   UPDATE_COURSE_POSTS_START: "UPDATE_COURSE_POSTS_START",
   UPDATE_COURSE_POSTS_SUCCESS: "UPDATE_COURSE_POSTS_SUCCESS",
   UPDATE_COURSE_POSTS_FAILURE: "UPDATE_COURSE_POSTS_FAILURE",

   // PUBLISH A COURSE TYPES
   PUBLISH_COURSE_START: "PUBLISH_COURSE_START",
   PUBLISH_COURSE_SUCCESS: "PUBLISH_COURSE_SUCCESS",
   PUBLISH_COURSE_FAILURE: "PUBLISH_COURSE_FAILURE",

   // DELETE A COURSE TYPES
   DELETE_COURSE_START: "DELETE_COURSE_START",
   DELETE_COURSE_SUCCESS: "DELETE_COURSE_SUCCESS",
   DELETE_COURSE_FAILURE: "DELETE_COURSE_FAILURE",
};
